version: "3.9"

services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./data/db/:var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=DocumentV
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=doc_dev_test
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Document_verifier
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
